apiVersion: v1
kind: Service
metadata:
  name: sales-rabbit
spec:
  selector:
    app: sales-rabbit
  ports:
  - port: 5672
    name: ampq-port
    targetPort: 5672    
  - port: 25676
    name: server-port
    targetPort: 25676 
  - port: 15672
    name: admin-port
    targetPort: 15672 
  type: ClusterIP