apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api-deployment
spec:
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
      - name: product-api
        image: rafaquintarelli/product-api:alpha
        ports:
        - containerPort: 8081
        resources: {}
        env:
          - name: PORT
            value: "8081"
          - name: API_SECRET
            value: YXV0aC1hcGktc2VjcmV0LWNvbnRhaW5lci0xMjM0NTY=
          - name: DB_HOST
            value: product-db
          - name: DB_NAME
            value: product-db
          - name: DB_USER
            value: admin
          - name: DB_PASSWORD
            value: "123456"
          - name: DB_PORT
            value: "5432"
          - name: RABBIT_MQ_HOST
            value: sales-rabbit
          - name: RABBIT_MQ_PORT
            value: "5672"
          - name: RABBIT_MQ_USER
            value: guest
          - name: RABBIT_MQ_PASSWORD
            value: guest
          - name: SALES_HOST
            value: sales-api
          - name: SALES_PORT
            value: "8082"