apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-api-deployment
spec:
  selector:
    matchLabels:
      app: sales-api
  template:
    metadata:
      labels:
        app: sales-api
    spec:
      containers:
      - name: sales-api
        image: rafaquintarelli/sales-api:alpha
        ports:
        - containerPort: 8082
        resources: {}
        env:
          - name: PORT
            value: "8082"
          - name: API_SECRET
            value: YXV0aC1hcGktc2VjcmV0LWNvbnRhaW5lci0xMjM0NTY=
          - name: MONGO_DB_URL
            value: mongodb://admin:123456@sales-db:27017/sales
          - name: RABBIT_MQ_URL
            value: amqp://guest:guest@sales-rabbit:5672/
          - name: PRODUCT_API_URL
            value: http://product-api:8081/api/product
          - name: NODE_ENV
            value: container