apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
      - name: auth-db
        image: postgres:alpine
        ports:
        - containerPort: 5432
        resources: {}
        env:
          - name: POSTGRES_DB
            value: auth-db
          - name: POSTGRES_USER
            value: admin
          - name: POSTGRES_PASSWORD
            value: "123456"