apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: tutum/mongodb
        ports:
        - containerPort: 27017
        resources: {}
        env:
          - name: MONGODB_USER
            value: admin
          - name: MONGODB_DATABASE
            value: sales
          - name: MONGODB_PASS
            value: "123456"